server:
  port: 1234
  
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FitnessTracker
    username: sandy
    password: sandy
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect